### ISSUE TITLE
Add separate minimal webpack configs for production and dev

### ISSUE THREAD

**Issue by Frixoe** [f-prime/electron-react-boilerplate-minimal#1]
I understand that this project is supposed to be a minimal version of the `electron-react-boilerplate` but another command in the `package.json` and a new file to build for production shouldn't hurt.

Hope you consider this.

Also, thanks for making this project.

**Comment by f-prime** [comment]
Ah, very good idea. I did not intentionally leave that out so I will add it.

Also, I was thinking about removing the redux dependency and making the default component use React Hooks instead. Thoughts?

Thank you for creating this issue.

**Comment by Frixoe** [comment]
Personally, I try to avoid using Redux whenever I can. However, on the web when using React, I don't really have a choice.

But since, we're not on the web anymore, might I suggest the addition of [`electron-store`](https://github.com/sindresorhus/electron-store) which manages app state by creating files which can be obfuscated(not encrypted) with the help of famous encryption algorithms. It's also extremely simple and light weight which fits the *minimal* theme of this project.

Let me know what you think.

**Comment by f-prime** [comment]
I will look into integrating electron-store. Why do you say that you do not have a choice on the web? React Hooks (https://reactjs.org/docs/hooks-intro.html) were released in React 16.8 and they make it much easier to write apps without using Redux. I am trying hard to keep everything as slim as possible.  So here is what I am probably going to do:

1. Add a production build command in the `package.json`
2. Remove Redux and Redux Thunk then create the demo using React Hooks instead with `reactn`
3. Look into using `electron-store` for persisting the state.

**Comment by Frixoe** [comment]
I honestly had no idea about React Hooks. I've only started using React a few weeks ago.

Also, those modifications sound great. Thanks.

**Comment by f-prime** [comment]
I am going to think more about adding `electron-store` but I have just made an update that implements the `npm run build` command for creating production builds. I also removed Redux + Redux Thunk and moved to using Hooks. A more lightweight solution I'd say.

Thanks again for the issue! Any improvements that you'd like to see in the future just let me know :)

**Comment by Frixoe** [comment]
Thanks a lot for the update! You have helped out a lot by making this project.

Really hope this repo stays up to date! :smiley:
